name: Dev API Continuous Deployment

on: [ push ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      IMAGE_NAME_DISCORD_BOT: dev-api-discord-bot
      IMAGE_HASH: $(echo $GITHUB_SHA | cut -c 1-6)
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v2

      - name: Docker login
        run: echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin

      - name: Build and push discord bot image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME_DISCORD_BOT:$IMAGE_HASH bot
          docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME_DISCORD_BOT:$IMAGE_HASH