name: Dev API Continuous Deployment

on: [ push ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v2

      - name: Hello
        run: sudo docker ps


